developit/htm

- src/index.mjs
- test/index.test.mjs
PR #38 introduces a new custom parser implementing the complete JSX syntax. This pull request adds tests to some corner cases, and suggests fixes for them:
* JSX allows property names that contain hyphens. This can be fixed by JSON.stringifying the property names.
* Boolean attributes following non-boolean ones got ignored (e.g. `<a b="1" c />` yielded the result `h('a', { b: '1' })`. This can be fixed by switching to MODE_WHITESPACE when we encounter a whitespace (and after calling `commit()`).
* `out.replace(/,\(\{(.*?)$/, ',Object.assign({},{$1')` gave unexpected results when there were multiple elements with spreads (because e.g. `"aba".replace(/a.*?$/, "x")` returns `"x"`) as well as attribute values containing the (sub)string `,({`. This can be fixed by separately keeping track of …
> Fix some corner cases in the custom JSX parser and add tests

- src/index.mjs
- test/index.test.mjs
This pull request fixes the error introduced in #39, where multiple spread props in one element caused faulty javascript to be generated. Added a test for the case.
> Fix multiple spread props in one element

- src/index.mjs
- test/index.test.mjs
This pull request implements the following fixes and modifications:
* Get rid of the `.endsWith` usage, making the library more compatible. Generated functions now avoid empty objects, so `<a ...${{ foo: 'bar' }} />` produces `h('a', Object.assign({}, $_h[1]))` instead of `h('a', Object.assign({}, $_h[1], {}))`. This is done by keeping track of the characters needed to close the current props section and the possible current spread. The tracked characters also double as flags, empty string being false.
* Fix cases where atext part contains a lone single or double quote, such as `<a>foo "<b /></a>`. Add a related test.
* The whitespace normalization pattern `replace(/^\s*\n+\s*|\s*\n+\s*$/g,'')` was susceptible to [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_ …
> Don't use endsWith, produce cleaner output, fix text with a lone quote

- src/index.mjs
- test/index.test.mjs
This pull request modifies the cache key generation to use `JSON.stringify`. With this the cache key is guaranteed to be unique for every unique array of statics, as two different arrays should not have identical JSON serializations.
JSON.stringify is now stored to a module-scoped variable, to cut down the size. This seems to give a (surprising) performance boost in my environment. I suspect this is highly JavaScript engine specific. Benchmarks below.
**Before change:**
`Creation: 36985/s, average: 0.027037810036229928ms`
**After change:**
`Creation: 45726/s, average: 0.02186895613191043ms`
The compressed code size also decreased somewhat.
**Before change:**
```
Build "htm" to dist:
625 B: htm.mjs.gz
572 B: htm.mjs.br
690 B: htm.umd.js.gz
623 B: htm.umd.js.br
```
**After change:**
``` …
```
> Use JSON.stringify for cache key generation

- packages/babel-plugin-htm/index.mjs
- src/index.mjs
- test/babel.test.mjs
- test/index.test.mjs
This pull request reorganizes the Babel plugin and adds tests, with the following steps:
1. In `treeify` the template is evaluated and converted to a object tree with `h(tag, props, ...children) { return { tag, props, children }; }`. `h` is intentionally as simple as possible, because there's a not-so-pretty trick: `Object.assign` is temporarily replaced with our own function that doesn't smush its arguments together, but just returns them as an array. This allows us to simplify props handling and do some optimizations to the output.
2. Return `Object.assign` back to the value it was before evaluating the template.
3. The resulting tree is transformed recursively, top-down in `transform`.
In `transform` the `props` argument is now either an array (from the `Object.assign` trick), `null` …
> Reorganize the Babel plugin, add support for non-literal template variables

- src/index.mjs
Because the function name `$_h` is not a placeholder in the new custom parser it can be replaced with something shorter - like `$`. This shaves off few bytes from the code size (584 B for htm.mjs.br instead of 588 B).
> Use $[] instead of $_h[] inside the generated functions

- src/integrations/preact/index.d.ts
The TypeScript definition misses a `Component` export from preact. This PR imports the Component class from "preact" and exports it in the definition file.
> Add missing Component export from Preact integration

- test/perf.test.mjs
This pull request modifies the branch `perf-test-harness`'s performance test file `perf.test.mjs` to use tagged templates whenever possible. This likely gives a better picture how e.g. caching is going to work in practice.
> Use tagged templates whenever possible in perf tests

- packages/babel-plugin-transform-jsx-to-htm/index.mjs
- test/babel-transform-jsx.test.mjs
This pull request adds an option to the babel-plugin-transform-jsx-to-htm for importing the tag. The option name is `import` and it can have three kinds of values: `false`, an **object** or a **string**:
* `false` is the default, any kind of importing won't happen and the plugin works as it previously did.
* An **object** has two keys: `module` and `export`. `module` defines which module gets imported, and `export` defines which name from the module gets imported. If `export` is `"default"` then the default export gets imported and if `export` is `"*"` then the whole namespace gets imported. Examples:
* `{ tag: "html", import: { module: "htm/preact", export: "html" } }` adds `import { html } from "htm/preact"` to the beginning of each file containing JSX.
* `{ tag: "$html", import: { …
> Add import option to babel-plugin-transform-jsx-to-htm

- package.json
- packages/babel-plugin-transform-jsx-to-htm/README.md
- packages/babel-plugin-transform-jsx-to-htm/index.mjs
- test/babel-transform-jsx.test.mjs
This pull request makes some cleanups to the babel-plugin-jsx-pragmatic package:
* Remove the `html` option from the plugin, as the output won't be strictly HTML compatible anymore anyway.
* Remove the dependency to babel-plugin-jsx-pragmatic, as the new `import` option replaces it for what it was used previously.
* Add a rudimentary beginnings of documentation for the new `import` option. Removed lit-html references, as babel-plugin-transform-jsx-to-htm is supposed to only work with HTM.
> Cleanups to jsx-to-htm: remove html option & dependency to babel-plugin-jsx-pragmatic, update README.md

- .gitignore
- package.json
- src/integrations/react/index.d.ts
- src/integrations/react/index.mjs
- src/integrations/react/package.json
This makes the Babel setup super easy for React too:
```js
["transform-jsx-to-htm", {
"import": "htm/react"
}]
```
> Add React integration

- package.json
This pull request fixes the mini builds that weren't as mini as they could be. The mini versions were built by microbundle with the parameter `--alias ./constants=./constants-mini`. However, the `.mjs` file extensions should also be included there, because actual import is `import { MINI } from './constants.mjs'` (note the `.mjs` there).
Props to @developit for spotting the extra code in https://unpkg.com/htm@2.1.0/mini/index.mjs (look for the pieces of code mentioning `Map`, they shouldn't be there).
> Fix mini builds, add the .mjs file extension to module aliases

- README.md
This pull request updates the README.md file in the following ways:
* Reduce the library size to < 600 bytes
* Mention the < 400 byte `htm/mini`
* Mention fragment support & add an example
* Update the version number to 2.1.0 in the last paragraph
> Mention fragment support & htm/mini in README.md

- packages/babel-plugin-transform-jsx-to-htm/package.json
Fixes #83 
The ES module version does not works because the @babel/plugin-syntax-jsx dependency is published as a cjs module
Maybe can fix #86
> babel-plugin-transform-jsx-to-htm: remove package.json module field

- packages/babel-plugin-transform-jsx-to-htm/index.mjs
- test/babel-transform-jsx.test.mjs
Makes jsx to htm babel transform handle JSX fragments both React.Fragment and short (<></>) syntax.
Basically removes the fragment nodes
> babel-transform-jsx: handle JSX fragments

- packages/babel-plugin-transform-jsx-to-htm/index.mjs
In JSX, a leading underscore in tag names denotes a reference tag (Component):
```js
var x = <_Foo />
// should output:
var x = html`<${_Foo} />`
```
> jsx-to-htm: leading underscore = reference tag

- packages/babel-plugin-transform-jsx-to-htm/index.mjs
- test/babel-transform-jsx.test.mjs
This pull request is an offshoot of #85 (by @blikblum), and modifies babel-plugin-transform-jsx-to-htm to support dotted component names like `<a.b.c />`.
The new logic considers all element names that either start with a capital letter, `$` or `_` or are not valid identifiers as component references. It should be noted that dotted names (member expressions) such as `a.b.c` are not valid identifiers, and are therefore considered to be component references.
This PR also adds tests for dotted components. There are also new tests for special-cased component names such as `$foo` and `_foo` (introduced in #92).
> Add dotted component name support for babel-plugin-transform-jsx-to-htm

- packages/babel-plugin-htm/index.mjs
- test/babel.test.mjs
This pull request adds support for native object spreads for babel-plugin-htm. Setting the new `useNativeSpread` parameter to `true` turns the support on. When the support is on input such as `<div ...${a} b=${1} ...${c} />` would produce `h("div", {...a, b:1, ...c})` instead of `h("div", Object.assign({}, a, {b:1}, c))` .
This PR also adds tests for the new functionality.
> Add native object spread support to babel-plugin-htm

- package.json
It's not great, but we weren't going to be using them to limit version compat anyway.
Fixes #94.
> Remove peerDependencies to avoid warnings

- packages/babel-plugin-htm/index.mjs
- test/index.test.mjs
This pull request fixes issue #104, making babel-plugin-htm act correctly for non-element roots. For example text-only roots (``` html`foo` ```) or mixed text/dynamic roots (``` html`foo${1}bar` ```) should now work. This is done by unifying how root nodes and child nodes are handled, essentially simplifying the plugin code.
This PR also add tests for the fixed behavior (that fail without the fix).
Fixes #104.
> Fix babel-plugin-htm behavior for non-element roots

- packages/babel-plugin-htm/README.md
This pull request documents the new `useNativeSpread` option in `babel-plugin-htm`'s readme file.
> Document babel-plugin-htm's new useNativeSpread option

- README.md
- package.json
- packages/babel-plugin-htm/package.json
- packages/babel-plugin-transform-jsx-to-htm/package.json
This pull request prepares the repository for the next release:
* Update the package.json files to the version number 2.2.0, except for `babel-plugin-transform-jsx-to-htm`s being bumped to 1.1.0.
* Update the main README.md file to mention the HTML comment support and the slightly increased `htm/mini` size.
> Prepare README.md and package.json files for a new release

- README.md
- src/build.mjs
- test/index.test.mjs
This pull request modifies the parsing logic (and adds related tests) so that slashes in unquoted property _values_ are allowed. For example `<abba prop=val/ue><//>` parses to `h('ab', { prop: 'val/ue' })`. The exception is when the `/` is immediately followed by `>` - `<abba prop=value/>` parses as a self-closing element `h('ab', { prop: 'value' })`.
Slashes in tag names and property names will still self-close the element. For example `<ab/ba prop=value>` parses to `h('ab', null)`, and `<abba pr/op=value>` parses to `h('abba', { pr: true })`.
The regular build size grows by 8 bytes (588 B -> 596 B) and the mini build size grows by 9 bytes (417 B -> 426 B). The performance doesn't seem to be affected, based on `test:perf` runs with V8 on MacOS 10.14.6.
Closes #106.
> Allow slashes in unquoted prop values (unless immediately followed by >)

- README.md
The `.mjs` link does not work anymore. Changing README to point to `.module.js` instead.
Closes 113
> Update link to standalone preact+html module

- package.json
- src/integrations/preact/index.mjs
- test/preact.test.mjs
This pull request updates the Preact version from which `htm/preact/standalone.*` files are built to `^10.0.0`.
One test needed to be modified, as it depended on a specific attribute order in the output.
> Update htm/preact/standalone to Preact X

- package.json
- src/index.d.ts
This pull request adds basic TypeScript type declarations for `htm`.
The typings are rather minimal. Only `htm`'s default export is typed, and it's just an object with one method: `bind(h)`. Here `h` is the pragma function and its argument types are quite lax for convenience's sake. `bind`'s result is a function whose return type is based on `h`'s return type:
```ts
// const html: (strings: TemplateStringsArray, ...values: any[]) => number | number[]
const html = htm.bind((type, props, ...children) => {
return children.length;
});
```
The type declarations are located in `src/index.d.ts`. That file is then copied to `dist/index.d.ts` and `mini/index.d.ts` as a part of the build process, after Microbundle has done its magic.
> Add TypeScript typing files for htm

- src/build.mjs
- src/index.mjs
- test/statics-caching.test.mjs
This pull request modifies `htm`'s caching strategy in three major ways:
* Use only `Map` for caching, getting rid of the previous fallback to string-keyed caching. This saves about 50 bytes in the brotli-compressed bundle.
* Create a separate cache for each `htm.bind(h)` call, which allows us to...
* Add static subtree caching. In short this means that HTM tracks the _staticness_ of subtrees it evaluates, and caches `h(...)` call results for static subtrees. In short it's kind of like a on-the-fly [@babel/plugin-transform-react-constant-elements](https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements/) (though less clever as even immutable dynamic properties/tags/chidren will prevent caching).
In this context by _static_ we mean a subtree where the root element and …
> Use only Map for caching & add static subtrees caching

- src/integrations/preact/standalone.mjs
This adds exported preact/hooks functions to the standalone bundle, so that one can use htm + preact + useState etc from a single module.
I believe that Preact 10.0.0+ gains a lot from using hooks, also this functionality was requested in the relevant issue issue: https://github.com/developit/htm/issues/46#issuecomment-544104401
There might be a better way to resolve this, if so - I'd be happy to adjust the PR.
> add preact hooks to the standalone bundle

- src/build.mjs
- test/statics-caching.test.mjs
This pull request modifies the `evaluate` function by adding more granular tools for tracking the staticness of a vnode and its children inside a `h` function.
HTM already automatically tracks and caches completely static subtrees (see #132). The tracking & caching process is completely transparent for the `h` function. That being said, there are still some hypothetical optimization possibilities if `h` functions got some more (optional) information. For example, vnodes with static props but some dynamic children would not fall under the "completely static subtree" umbrella that #132 optimizes. A VDOM-based UI framework could still use that staticness information to skip diffing such nodes and jump directly into diffing their children.
This PR adds two tools for exploring such …
> Add helpers for tracking subtree staticness inside `h` functions

- README.md
- package.json
- packages/babel-plugin-htm/package.json
- packages/babel-plugin-transform-jsx-to-htm/package.json
This pull request prepares for the v3 release by:
* bumping the htm package version to 3.0.0
* bumping the babel-plugin-transform-jsx-to-htm version to 3.0.0 (from 2.2.0) and requiring htm ^3.0.0
* bumping the babel-plugin-htm version to 2.0.0 from 1.1.0 and requiring htm ^3.0.0
* adding minor tweaks to README.md
> Prepare README.md and package.json files for v3 release

- src/integrations/preact/standalone.mjs
I *think* this fixes the issue I was scratching my head at!
fixes #145
> add createContext to preact standalone bundle

- test/statics-caching.test.mjs
This pull request adds a test, checking that the `h` function can modify the staticness flags in `this[0]` to explicitly tell HTM to consider the current subtree as static.
The tests define a wrapper function for our `h` that flips the two lowest bits in `this[0]` to zero whenever we want to force the current subtree to be considered static:
```js
function wrapH(h) {
return function(type, props, ...children) {
if (type === '@static') {
this[0] &= ~3;
return children;
}
if (props['@static']) {
this[0] &= ~3;
}
return h(type, props, ...children);
};
}
const html = htm.bind(wrapH(h));
```
After this a magical `@static` prop allows forcing the subtree to be built only once:
```js
html`
<div @static>
${ items.map(x => <li>${x.name}</li>) }
<//>
`
```
`@static` also works as a tag name when we …
> Add a test for forcing subtree staticness

- package.json
This pull request fixes the TypeScript typings file name from "dist/index.d.ts" to "dist/htm.d.ts". It also adds the package.json field "types" to explicitly point to the typings file.
> Fix typing file name & package.json field

- src/index.d.ts
Resolves #152.
`index.d.ts` should export the identified value with declared type, not the actual type.
> Fix typing: export the identified w/ declared type

- src/integrations/preact/standalone.mjs
- test/preact.test.mjs
I had "patched" the Preact integrations to automatically pass `replaceNode` for Preact 8 when we initially launched HTM. When we updated to Preact X, that patch was [correctly removed](https://github.com/developit/htm/commit/66f8ef8650f2a93627ea800eabc6006c82562f23#diff-3b5071effb1fb5ba4fe6eb2fdd26680bL17-L20) for `htm/preact`, but we forgot `htm/preact/standalone`. This just copies that change over, and fixes #159.
See [additional codepen repro](https://codepen.io/developit/pen/VwvebLQ?editors=0010) (line 55)
> Fix render() in standalone build (fixes #159)

- .github/workflows/test.yml
- .gitignore
- package.json
- test/fixtures/esm/index.js
- test/fixtures/esm/package.json
Creates conditional export that points "import" conditional exports to mjs files. This lets node load the esm version without having to set "type": "module" on the main package.json.
This is similar to the approach in the main preact repo - https://github.com/preactjs/preact/pull/2451
> Support node v13 with es modules

- packages/babel-plugin-transform-jsx-to-htm/index.mjs
This makes `terse:true` match Babel's [default JSX whitespace behaviors](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=PTAEAECsGcA9QBYCgkB4AmBLAbgPiaKAIYDeA5AEZkC-AxmsFngNwoY76FGjlXWj1UjDqzRNOxQoQpSBBUOnmyApkgBmDcaNQAHAE7KJ3KTKn1Ci2YVUah-w9vHzU3YLh6Uag4SzZPCLqBuoKgybpoifhzOrhKhQfhCWlF4MQlIMqi06UmRYtEBsaAUztnhub5ocUXx5W6iQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.12.10&externalPlugins=).
/cc @cristianbote
> Collapse whitespace when { terse: true }

- package.json
- src/integrations/preact/standalone.mjs
This exposes the `useErrorBoundary` hook for the standalone preact bundle.
> Export useErrorBoundary hook

- packages/babel-plugin-transform-jsx-to-htm/index.mjs
- test/babel-transform-jsx.test.mjs
This pull request fixes the babel-plugin-transform-jsx-to-htm plugin output for JSX inputs like this:
```jsx
<>
<Foo />
{Bar}
</>
```
Before the fix the plugin crashes with the following error message:
```
Number of TemplateLiteral quasis should be exactly one more than the number of expressions.
Expected 3 quasis but got 2
```
The fix is to always ensure that a template literal expression ends with a quasi, even when the quasi is an empty string. New static string content is then always applied to the (currently) last quasi in the template. When an expression is added a new empty quasi is immediately appended after that.
Kudos to @cristianbote for noticing a problem on [wmr](https://github.com/preactjs/wmr) output that was caused by this issue. It appears that this fix also fixes the wmr …
> Ensure that template literals generated by JSX-to-HTM transform has a balanced amount of quasis and expressions

- package.json
Reference: https://github.com/jspm/project/issues/100#issuecomment-810644748
Hi, I find an issue with my package's exports and looks like it applies `htm` too. 
Preact also keeps them in that order https://github.com/preactjs/preact/blob/master/package.json
> Reorder exports

- .github/workflows/test.yml
Node 12 has been the oldest LTS for a while now.
> Skip running tests on outdated Node 10

- package.json
* as per https://github.com/microsoft/TypeScript/issues/48235#issuecomment-1067363731
* follow-up https://github.com/preactjs/preact/pull/3513
> Fix nodenext module support from TypeScript 4.7

- packages/babel-plugin-htm/README.md
I just tried this in our repo, and it works just fine. The `import` property is taken verbatim into the transformed code (fortunately!).
> Fixed babel-plugin-htm's documentation of `import` options
